language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jekyllrb-gulp' ]; then cd .. && eval "mv $currentfolder generator-jekyllrb-gulp" && cd generator-jekyllrb-gulp; fi

